---
name: basis
version: 0.03
author:
  - 'Sebastian Knapp <sk@computer-leipzig.com>'
abstract: ~
license: perl
requires:
  Sub::Uplevel: 0.12
  perl: 5.6.0
build_requires:
  Test::More: 0
provides:
  basis:
    file: lib/basis.pm
    version: 0.03
generated_by: Module::Build version 0.26
